//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWPlatform.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WWPlatformEntities : DbContext
    {
        public WWPlatformEntities()
            : base("name=WWPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Catalog> catalogs { get; set; }
        public DbSet<Subtype> subtypes { get; set; }
        public DbSet<Dynasty> dynasties { get; set; }
        public DbSet<Feature> features { get; set; }
        public DbSet<Lectuer> lectuers { get; set; }
        public DbSet<Webcast> webcasts { get; set; }
        public DbSet<Offering> offerings { get; set; }
        public DbSet<SiteUser> siteusers { get; set; }
        public DbSet<HintTag> hinttags { get; set; }
        public DbSet<Script> scripts { get; set; }
        public DbSet<Book> books { get; set; }
        public DbSet<Chapter> chapters { get; set; }
        public DbSet<Section> sections { get; set; }
    }
}
