//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWPlatform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtype
    {
        public Subtype()
        {
            this.Offerings = new HashSet<Offering>();
        }
    
        public int Idkey { get; set; }
        public string Title { get; set; }
        public bool Hot { get; set; }
    
        public virtual ICollection<Offering> Offerings { get; set; }
    }
}
